name: portfolio_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.4
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/profile_picture.png
    - assets/flutter_logo.png
    - assets/nodejs_logo.png
    - assets/express_logo.png
    - assets/postgresql_logo.png
    - assets/api_logo.png
    - assets/cloud_logo.png
